---
sv_port: '7777'

#Player Initial Options
player_health: 40
player_bullets: 12
player_max_bullets: 100
player_mask_radio: 5
player_lives: 3
player_respawn_bullets: 8
player_pace: 1
player_rotation_angle: 0.1

#Guns
knife_range: 2

chain_cannon_bullet_required: 10
chain_cannon_base_precision: 10

pistol_bullet_required: 10
pistol_base_precision: 10

rocket_launcher_bullet_required: 10
rocket_launcher_base_precision: 10

machine_gun_bullet_required: 10
machine_gun_base_precision: 10

#Items
items_mask_radio: 0.5
food_health_recovered: 10
medic_kit_health_recovered: 20
blood_health_recovered: 1
blood_health_recovered_if_less_than: 11
bullets_amount: 5
bullets_respawn_amount: 10
drop_distance_from_dead_player: 2

crosses_points: 10
cup_points: 50
chests_points: 100
crown_points: 200
