---
sv_host: 'localhost'
sv_port: '8080'

# Rendering Options
screen_width: 960
screen_height: 600
fullscreen: false
fps: 30

# Sound Options
music_volume: 0
effect_volume: 50

# Player Initial Options
player_health: 100
player_bullets: 80
player_max_bullets: 100
player_mask_radio: 0.4
player_lives: 3
player_max_points: 999999
player_respawn_bullets: 8
player_speed: 0.1
player_rotation_speed: 0.1
player_knife_mask_radio: 10 # > player_mask_radio
player_ghost_speed: 0.2

# Bot
bot_positions_difference_allowed: 1 #less than knife_range

# Guns
bullet_max_damage: 10

knife_range: 1.6

pistol_range: 20
pistol_bullet_required: 1
pistol_spray: 0.17453
pistol_std_dev: 0.1

machine_gun_range: 60
machine_gun_bullet_required: 1
machine_gun_burst_frequency: 3333
machine_gun_shot_frequency: 200
machine_gun_spray: 0.261799
machine_gun_std_dev: 0.2

chain_cannon_range: 40
chain_cannon_bullet_required: 1
chain_cannon_frequency: 100
chain_cannon_spray: 0.349066
chain_cannon_std_dev: 0.2

rocket_launcher_bullet_required: 5


# Items
items_mask_radio: 0.5
food_health_recovered: 10
medic_kit_health_recovered: 20
blood_health_recovered: 1
blood_health_recovered_if_less_than: 11
bullets_amount: 5
bullets_respawn_amount: 10
drop_distance_from_dead_player: 1

cross_points: 10
cup_points: 50
chest_points: 100
crown_points: 200

# Solid Objects
pillar_radius: 0.5
table_width: 1.0
table_depth: 1.0
barrel_radius: 0.5
rocket_radius: 0.1
rocket_speed: 0.2
rocket_explosion_radius: 2.0
rocket_max_damage: 40
rocket_min_damage: 10

# Other
first_id: 1
match_length: 10
door_timer: 5
door_speed: 1.0 
